### ISSUE TITLE
trouble running the app

### ISSUE THREAD

**Issue by ETAmundson** [rwev/bible#2]
Hi, I'm very interested in your app but when I try to run the app, my terminal says "AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren' ". Is there something else I need to run this app? I have Python 3.9 if that's relevant. I dropped a picture of what my terminal spits out when I try to run the bible command.

![TerminalBible](https://user-images.githubusercontent.com/62269687/105253665-eb1ba900-5b4d-11eb-991b-b37c8de2fced.png)

**Comment by rwev** [comment]
Hi, thanks for reporting this!

I am also running Python 3.9 on iOS but don't get this error.

Did you by chance install it using the command in the README? It seems like this error could be related to missing XML data included in the manifest. 

Trying uninstalling and reinstalling: 
```shell
python3 -m pip uninstall bible
python3 -m pip install https://github.com/rwev/bible/archive/master.zip
```

**Comment by rwev** [comment]
Hey @ETAmundson, were you able to get it working?

**Comment by ETAmundson** [comment]
Hey I just saw this today and ran the 2 commands now it's just saying that it doesn't know what reader is for some reason.
![Screenshot from 2021-02-11 00-04-46](https://user-images.githubusercontent.com/62269687/107604101-eef69480-6bfc-11eb-925d-7c9dfe0e1c6d.png)

**Comment by rwev** [comment]
Ok, that was an issue introduced by a PR, and it has since been fixed. If you are able to give it a shot again, please let me know what happens.

**Comment by ETAmundson** [comment]
I figured it out! There was a deprecated method call in my python3.9/site-packages/hyphen/dictools.py file.
