### ISSUE TITLE
Chapternumber should become visible when "cursor" is on them. 

### ISSUE THREAD

**Issue by jajpater** [rwev/bible#5]
When a Biblebook has more chapters than numbers visible on the screen you can navigate to the chapternumber but the chapternumber will not become visible. For instance the book of Genesis has 50 chapters only numbers 1 to 47 are visible for me, I can reach 50 but I can't see the chapter number or the cursor.

**Comment by jajpater** [comment]
[![asciicast](https://asciinema.org/a/pax4detE7HmtRFzbhIsuBNL6f.svg)](https://asciinema.org/a/pax4detE7HmtRFzbhIsuBNL6f)

**Comment by rwev** [comment]
Thanks for reporting this; I just confirmed the bug locally.

**Comment by rwev** [comment]
Fixed. I had to remove the `G` (jump to end) vim-style keybinding because it isn't compatible with how the displayed boundaries are managed.
